RunFitness/Areas/AdminRunFitness/Controllers/SuccessController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RunFitness.DAL;
using RunFitness.Extensions;
using RunFitness.Models;

namespace RunFitness.Areas.AdminRunFitness.Controllers
{
    [Area("AdminRunFitness")]
    [Authorize(Roles = "Admin")]
    public class SuccessController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IWebHostEnvironment _env;
        public SuccessController(AppDbContext db, IWebHostEnvironment env)
        {
            _db = db;
            _env = env;
        }
        public IActionResult Index()
        {
            return View(_db.Successes.Where(t => t.IsDeleted == false).ToList());
        }

        #region Update

        public IActionResult Update(int? id)
        {
            if (id == null) return NotFound();
            Success success = _db.Successes
                .Include(c => c.SuccessDetail).FirstOrDefault(c => c.IsDeleted == false && c.Id == id);
            if (success == null) return NotFound();
            return View(success);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, Success Success)
        {
            Success viewSuccess = _db.Successes.Include(c => c.SuccessDetail).FirstOrDefault(c => c.Id == id && c.IsDeleted == false);

            if (Success.Photo != null)
            {

                if (!Success.Photo.IsImage())
                {
                    ModelState.AddModelError("", "Bunu yaratmaq ucun wekil tipi yarat!!!");
                    return View(viewSuccess);
                }
                if (!Success.Photo.MaxSize(200))
                {
                    ModelState.AddModelError("", "Wekilin olcusu 200kb-dan az olmalidi!!!");
                    return View(viewSuccess);
                }

                string folder = Path.Combine("img", "stories");
                string fileName = await Success.Photo.SaveImgAsync(_env.WebRootPath, folder);
                Success.Image = fileName;
            }

            Success.IsDeleted = false;
            viewSuccess.Title = Success.Title;
            viewSuccess.Description = Success.Description;
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        #endregion

        #region Detail


        public IActionResult Detail(int? id)
        {
            if (id == null) return NotFound();
            Success success = _db.Successes.Include(c => c.SuccessDetail)
                .FirstOrDefault(c => c.IsDeleted == false && c.Id == id);
            if (success == null) return NotFound();
            return View(success);

        }

        #endregion
    }
}

RunFitness/Areas/AdminRunFitness/Views/Success/Detail.cshtml
@model Success
@{
    ViewData["Title"] = "Detail";
}
<div class="col-12">
    <img src="~/img/stories/@Model.Image" width="300" />
</div>
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Name:<br /><br /> @Model.Title</h4>
            <h4 class="card-title">Description:<br /><br /> @Model.Description</h4>
        </div>
    </div>
</div>
<a asp-action="Index" class="btn btn-secondary">Go Back</a>

RunFitness/Areas/AdminRunFitness/Views/Success/Index.cshtml
@model List<Success>
@{
    ViewData["Title"] = "Index";
}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body" style=" background-color: rgba(3,3,3,0.31);">
            <h4 class="card-title" style=" color: darkblue;">Success</h4>
            <div class="table-responsive" style=" background-color: rgba(3,3,3,0.34);">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th style=" color: white">
                                 Photo
                            </th>
                            <th style="color: white">
                                Title
                            </th>
                            <th style="color: white">
                                Description
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Success success in Model)
                        {
                            <tr>
                                <td style=" background-color: rgba(3,3,3,0.43)">
                                    <img class="img-fluid" src="~/img/stories/@success.Image"
                                         alt="trainer">
                                </td>
                                <td style=" background-color: rgba(3,3,3,0.40);color: white">
                                    @success.Title
                                </td>
                                <td style=" background-color: rgba(3,3,3,0.37);color: white">
                                    @success.Description
                                </td>
                                <td style=" background-color: rgba(3,3,3,0.37)">
                                    <a asp-controller="Success" asp-action="Detail" asp-route-id="@success.Id" class="btn btn-success"><i class="mdi mdi-information"></i></a>
                                    <a asp-controller="Success" asp-action="Update" asp-route-id="@success.Id" class="btn btn-warning"><i class="mdi mdi-table-edit"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

RunFitness/Areas/AdminRunFitness/Views/Success/Update.cshtml
@model Success
@{
    ViewData["Title"] = "Update";
}
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update Success</h4>
            <div class="text-danger" asp-validation-summary="ModelOnly"></div>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="@Model.Title">Title</label>
                    <input asp-for="@Model.Title" class="form-control" placeholder="Title">
                    <span class="text-danger" asp-validation-for="@Model.Title"></span>
                </div>
                <div class="form-group">
                    <label asp-for="@Model.Description">Description</label>
                    <input asp-for="@Model.Description" class="form-control" placeholder="Description">
                    <span class="text-danger" asp-validation-for="@Model.Description"></span>
                </div>
                <div class="form-group" id="photo">
                    <label asp-for="@Model.Photo"></label>
                    <input asp-for="@Model.Photo" class="form-control" placeholder="Select Photo">
                    <span class="text-danger" asp-validation-for="@Model.Photo"></span>
                </div>
                <button type="submit" class="btn btn-primary mr-2">Update</button>
                <a class="btn btn-light" asp-action="Index">Cancel</a>

            </form>
        </div>
    </div>
</div>
@section Scripts{
    <partial name="_Validation" />


}