RunFitness/Areas/AdminRunFitness/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RunFitness.DAL;
using RunFitness.Extensions;
using RunFitness.Models;
using RunFitness.ViewModels;

namespace RunFitness.Areas.AdminRunFitness.Controllers
{
    [Area("AdminRunFitness")]
    [Authorize(Roles = "Admin")]
    public class TableController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IWebHostEnvironment _env;
        public TableController(AppDbContext db, IWebHostEnvironment env)
        {
            _db = db;
            _env = env;
        }
        public IActionResult Index()
        {
            TableVM tableVM = new TableVM
            {
                Weeks = _db.Weeks.Include(w => w.TrainerWeeks).ThenInclude(w => w.Trainer)
               .ToList(),
                Times = _db.Times.Include(w => w.TrainerWeeks).ThenInclude(w => w.Trainer)
               .ToList(),
            };

            return View(tableVM);
        }





        #region Create

        public IActionResult Create()
        {
            GetTrainer();
            GetWeek();
            GetTime();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TrainerWeek trainerWeek, int? TrainerCtgId, int? TimeCtgId, int? WeekCtgId)
        {
            GetTrainer();
            GetWeek();
            GetTime();

           

            foreach (TrainerWeek tw in await _db.TrainerWeeks.ToListAsync())
            {
                if (WeekCtgId==tw.WeekId&& TimeCtgId==tw.TimeId)
                {
                    return View();
                }
            }
            
            trainerWeek.TrainerId = (int)TrainerCtgId;
            trainerWeek.WeekId = (int)WeekCtgId;
            await _db.TrainerWeeks.AddAsync(trainerWeek);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #region Create void

        public void GetTrainer()
        {
            ViewBag.Trainers = _db.Trainers.Where(t => t.IsDeleted == false).ToList();

        }
        public void GetWeek()
        {
            ViewBag.Week = _db.Weeks.ToList();

        }
        public void GetTime()
        {
            ViewBag.Time = _db.Times.ToList();

        }

        #endregion

        #endregion


        #region Deleted

        public async Task<IActionResult> Delete(int? id)
        {  

            ViewData["WeekkId"] = new SelectList(_db.Weeks, "Id", "Name"); 
            ViewData["TrainerId"] = new SelectList(_db.Trainers, "Id", "Name");


            //ViewBag["TimeId"] = _db.TrainerWeeks.Include(t => t.Time); 
            //ViewBag["TrainerId"] = _db.TrainerWeeks.Include(t => t.Trainer );

            if (id == null) return NotFound();
            Time times = _db.Times.Where(t=>t.Id==id).Include(t => t.TrainerWeeks).ThenInclude(t => t.Week)
                .Include(t => t.TrainerWeeks).ThenInclude(t=>t.Trainer).FirstOrDefault();
            if (times == null) return NotFound();
            return View(times);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int? id)
        {
            if (id == null) return NotFound();
            Time times = _db.Times.FirstOrDefault(c => c.Id == id);
            if (times == null) return NotFound();
            _db.Times.Remove(times);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion


        #region Update

        public IActionResult Update(int id)
        {
            GetTrainer();
            GetWeek();
            GetTime();
            TrainerWeek trainerWeek = new TrainerWeek
            {
                TimeId = id
            };
            return View(trainerWeek);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(TrainerWeek trainerWeek, int? TrainerCtgId, int? TimeCtgId, int? WeekCtgId)
        {
           

            var trainerWeek2 = await _db.TrainerWeeks.FirstOrDefaultAsync(t => t.TimeId == TimeCtgId && t.WeekId == WeekCtgId);
            trainerWeek2.TrainerId = (int)TrainerCtgId;
           

           
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        #endregion


    }
}

RunFitness/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RunFitness.DAL;
using RunFitness.Models;
using RunFitness.ViewModels;

namespace RunFitness.Controllers
{
    public class TableController : Controller
    {
        private readonly AppDbContext _db;
        public TableController(AppDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {


            TableVM table = new TableVM
            {
                Weeks = _db.Weeks.Include(w=>w.TrainerWeeks).ThenInclude(w=>w.Trainer)
                .Include(w=>w.TrainerWeeks).ThenInclude(w=>w.Time).ToList(),
                trainerWeeks = _db.TrainerWeeks.Include(w=>w.Trainer).Include(w=>w.Time).ToList(),
                Times=_db.Times.Include(t=>t.TrainerWeeks).ThenInclude(t=>t.Trainer).ToList(),
                Trainers =_db.Trainers.Include(t=>t.TrainerWeeks).ThenInclude(t=>t.Week).ToList(),
            };

            return View(table);
        }
    }
}

RunFitness/Areas/AdminRunFitness/Views/Table/Create.cshtml
@model TrainerWeek
@{
    ViewData["Title"] = "Create";
}
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Time</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group" id="MainCategory">
                    <label>Select Day</label>
                    <select class="form-control" name="WeekCtgId">
                        @foreach (Week weekCtg in ViewBag.Week)
                        {
                            <option value="@weekCtg.Id">@weekCtg.Name</option>
                        }
                    </select>
                </div>

                <div class="form-group" id="MainCategory">
                    <label>Select Time</label>
                    <input asp-for="@Model.Time.StartTime" class="form-control" placeholder="Time">
                    <span class="text-danger" asp-validation-for="@Model.Time.StartTime"></span>
                  
                </div>

                <div class="form-group" id="MainCategory">
                    <label>Select Trainer</label>
                    <select class="form-control" name="TrainerCtgId">
                        @foreach (Trainer tarinerCtg in ViewBag.Trainers)
                        {
                            <option value="@tarinerCtg.Id">@tarinerCtg.Name</option>
                        }
                    </select>
                </div>
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <a class="btn btn-light" asp-action="Index">Cancel</a>

            </form>
        </div>
    </div>
</div>

RunFitness/Areas/AdminRunFitness/Views/Table/Delete.cshtml
@model Time
@{
    ViewData["Title"] = "Delete";
}
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title"></h4>

            <div class="form-group" id="MainCategory">
                <label>Select Day</label>
                <select class="form-control">
                    @foreach (TrainerWeek time in Model.TrainerWeeks)
                    {
                        <option value="@time.Trainer.Id">@time.Trainer.Name</option>
                    }
                    </select>
                <select class="form-control">
                    @foreach (TrainerWeek time in Model.TrainerWeeks)
                    {
                        <option value="@time.Week.Id">@time.Week.Name</option>
                    }
                </select>
            </div>
             
        </div>
    </div>

</div>
<h3 class="text-danger">Are you surc?</h3>
<form method="post">
    <button type="submit" class="btn btn-danger">Delete</button>
</form>
<a asp-action="Index" class="btn btn-secondary mt-3">Go Back</a>

RunFitness/Areas/AdminRunFitness/Views/Table/Index.cshtml
@model TableVM
@{
    ViewData["Title"] = "Index";
}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body" style=" background-color: rgba(3,3,3,0.31);">
            <h4 class="card-title" style=" color: darkblue;">Table</h4>
            <a asp-controller="Table" asp-action="Create" class="btn btn-success">Create</a>
            <div class="table-responsive" style=" background-color: rgba(3,3,3,0.34);">
                <table class="table table-striped">
                   
                    <tbody>
                        <tr>
                            <th class="days t">Time</th>
                            @foreach (Week w in Model.Weeks)
                            {
                                <th class="days">@w.Name</th>
                            }
                        </tr>
                        @foreach (Time time in Model.Times)
                        {
                    <tr>
                        <th class="time">@time.StartTime</th>
                        @foreach (Week week in Model.Weeks)
                        {
                            bool IsEmpty = false;
                            <td>
                                @foreach (var item in week.TrainerWeeks.Where(rw => rw.WeekId == week.Id && rw.TimeId == time.Id))
                                {
                                     @item.Trainer.Name<br />
                                    IsEmpty = true;
                                }
                                @(IsEmpty==false?"__":" ")
                            </td>
                        }

                        <td style=" background-color: rgba(3,3,3,0.37)">
                            <a asp-controller="Table" asp-action="Update" asp-route-id="@time.Id" class="btn btn-warning"><i class="mdi mdi-table-edit"></i></a>
                            <a asp-controller="Table" asp-action="Delete" asp-route-id="@time.Id" class="btn btn-danger"><i class="mdi mdi-delete"></i></a>
                        </td>
                    </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

RunFitness/Areas/AdminRunFitness/Views/Table/Update.cshtml
@model TrainerWeek

@{
    ViewData["Title"] = "Update";
}
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update Time</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <input type="hidden" name="timeCtgId" value="@Model.TimeId" />
                <div class="form-group" id="MainCategory">
                    <label>Select Day</label>
                    <select class="form-control" name="WeekCtgId">
                        @foreach (Week weekCtg in ViewBag.Week)
                        {
                            <option value="@weekCtg.Id">@weekCtg.Name</option>
                        }
                    </select>
                </div>
                <div class="form-group" id="MainCategory">
                    <label>Select Trainer</label>
                    <select class="form-control" name="TrainerCtgId">
                        @foreach (Trainer tarinerCtg in ViewBag.Trainers)
                        {
                            <option value="@tarinerCtg.Id">@tarinerCtg.Name</option>
                        }
                    </select>
                </div>
                <button type="submit" class="btn btn-primary mr-2">Submit</button>
                <a class="btn btn-light" asp-action="Index">Cancel</a>

            </form>
        </div>
    </div>
</div>